### PR TITLE
Feature/travis ci

### PR DESCRIPTION
**Pull request by christophka**
Use the features of travis to speed up the CI stages.
Check the options on automatic deployment to GitHub Release/npm

### CODE REVIEW

**Comment by christophka** [comment]
@maschino 
I think I figured out how we could automatically deploy to npm, but I couldn't come up with a way to test it.

1. I added a deploy section in the travis file. That should be triggered, if tags are pushed - From my understanding, that should happen, if we create a "GitHub Release" with a tag.
2. To deploy to npm, the user must be authenticated. Therefore an [npm auth token](https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token) is needed. I added this as an env var for the travis CI processes. The env vars must be set over at travis-ci.com for the project ([here is an example](https://github.com/bcoe/travis-deploy-example#setting-npm_token-environment-variable)). I did the same think for the email address - so the 2 vars that must be set are `NPM_DEPLOY_EMAIL` and `NPM_API_KEY`
3. I added the `skip_cleanup` flag that should prevent travis from removing files created during the previous stages. I can't tell, if the travis jobs are executed on a "pushed" tag - i would expect that behaviour for the process to work. Otherwise, the "build" folder will be missing.

**Comment by christophka** [comment]
@maschino the npm deployment seems to work now.
The deployment can now be triggered by creating a tag, for example when a GitHub release is created.
What we could also do, is that we could also create an automated GitHub release with the package.

**Comment by maschino** [comment]
@christophka What do you mean with create an automated GitHub release? 

So we'd just create a new tag, push it and travis would create a new release on GitHub and deploy it on npm? What about the description of the release?

**Comment by christophka** [comment]
Yeah, exaclty that. You would locally run
`
yarn version --new-version X.X.X
git push --tags
`
And it would create
* A GitHub Release
* Deploy to npm

The release description body could be edited manually or we could link/upload the changelog. Extracting the content of the .md file seems to be a problem, though.

**Comment by christophka** [comment]
merged

**Pull request closed without merging**
